---
deployment:
  tasks:
    # Other all directory path
    - export DEPLOYPATH=/home/a1630xeb/testing.lakshyarth.com/
    # Public directory path
    - export DEPLOYPATH_PUBLIC=/home/a1630xeb/public_html/testing.lakshyarth.com/
    # - /bin/cp public $DEPLOYPATH_PUBLIC
    # - /bin/cp -R * $DEPLOYPATH_HOME
    - /bin/cp -R public $DEPLOYPATH_PUBLIC

    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R route $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R .cpanel.yml $DEPLOYPATH
    - /bin/cp -R .editorconfig $DEPLOYPATH
    # - /bin/cp -R .env $DEPLOYPATH
    - /bin/cp -R .env.example $DEPLOYPATH
    - /bin/cp -R .gitattributes $DEPLOYPATH
    - /bin/cp -R .gitignore $DEPLOYPATH
    - /bin/cp -R .styleci.yml $DEPLOYPATH
    - /bin/cp -R artisan $DEPLOYPATH
    - /bin/cp -R composer.json $DEPLOYPATH
    - /bin/cp -R composer.lock $DEPLOYPATH
    - /bin/cp -R package-lock.json $DEPLOYPATH
    - /bin/cp -R package.json $DEPLOYPATH
    - /bin/cp -R phpunit.xml $DEPLOYPATH
    - /bin/cp -R postcss.config.js $DEPLOYPATH
    - /bin/cp -R README.md $DEPLOYPATH
    - /bin/cp -R server.php $DEPLOYPATH
    - /bin/cp -R tailwind.config.js $DEPLOYPATH
    - /bin/cp -R vite.config.js $DEPLOYPATH
    - /bin/cp -R webpack.mix.js $DEPLOYPATH
